kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: web-effs
  namespace: myns
provisioner: ma/web-efs
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: effs-mysql
  annotations:
    volume.beta.kubernetes.io/storage-class: "web-efs"
  namespace: myns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: effs-web
  annotations:
    volume.beta.kubernetes.io/storage-class: "web-efs"
  namespace: myns
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
       
      storage: 10Gi